version: "3.3"
services:
  backend:
    build: ./api
    container_name: emphasoft_backend
    environment:
      PRODUCTION: 'yes'
    ports:
      - "1984:1984"
    command: bash -c "python -m api.main"
    depends_on:
      - db
  frontend:
    build: ./frontend/emphasoft-front
    container_name: emphasoft_frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
  db:
    image: postgres:12
    container_name: emphasoft_postgres
    environment:
      POSTGRES_DB: emphasoft_db
      POSTGRES_USER: emphasoft_user
      POSTGRES_PASSWORD: 123456
    volumes:
      - ./postgres/pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  pgdata:
