version: "3.3"
services:
  backend:
    build: ./api
    ports:
      - "1984:1984"
    command: bash -c "python -m api.main"
    volumes:
      - image_data:/app/data
    depends_on:
      - db
  frontend:
    build: ./frontend/emphasoft-front
    ports:
      - "8080:8080"
    volumes:
      - image_data:/app/src/assets/avatars
    depends_on:
      - backend
  db:
    image: postgres:latest
    container_name: emphasoft_postgres
    environment:
      POSTGRES_DB: emphasoft_db
      POSTGRES_USER: emphasoft_user
      POSTGRES_PASSWORD: 123456
    volumes:
      - ./postgres/pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  pgdata:
  image_data:
